version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:

  flask_api:
    container_name: flask_api
    volumes:
      - "/path/to/local/static/img:/path/to/docker/static/img"
    build:
      context: ./bollards_api
      dockerfile: Dockerfile
    env_file:
      - api.env
    networks:
      - internal
      - web
    depends_on:
      - "db"
    restart: always

  db:
    container_name: db
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - db.env
    networks:
      - internal
    restart: always

volumes:
  postgres_data:
