version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - db.env
    restart: always

volumes:
  postgres_data:
