"""empty message

Revision ID: 0df26df10c9c
Revises: e43a5b92b0f5
Create Date: 2021-07-16 07:50:20.338772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df26df10c9c'
down_revision = 'e43a5b92b0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bimage', 'bollard_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bimage', 'bollard_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
