"""empty message

Revision ID: 104e00bffd09
Revises: 28143e062de0
Create Date: 2021-07-16 08:51:27.516048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104e00bffd09'
down_revision = '28143e062de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bollard_b_number_key', 'bollard', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bollard_b_number_key', 'bollard', ['b_number'])
    # ### end Alembic commands ###
