"""empty message

Revision ID: 637546220760
Revises: cab470effa98
Create Date: 2022-01-15 16:23:15.832527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637546220760'
down_revision = 'cab470effa98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bollard', sa.Column('b_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bollard', 'b_height')
    # ### end Alembic commands ###
