"""empty message

Revision ID: 81795095317e
Revises: 713fadf88be3
Create Date: 2021-08-07 15:21:47.355855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81795095317e'
down_revision = '713fadf88be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bollard', sa.Column('b_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bollard', 'b_type')
    # ### end Alembic commands ###
