"""empty message

Revision ID: cab470effa98
Revises: 81795095317e
Create Date: 2022-01-15 15:49:01.789516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab470effa98'
down_revision = '81795095317e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bollard', sa.Column('b_easting', sa.Numeric(precision=9, scale=1), nullable=True))
    op.add_column('bollard', sa.Column('b_northing', sa.Numeric(precision=9, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bollard', 'b_northing')
    op.drop_column('bollard', 'b_easting')
    # ### end Alembic commands ###
