"""empty message

Revision ID: d2cc758300bf
Revises: 00b26f48ff32
Create Date: 2021-07-12 13:48:30.929689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cc758300bf'
down_revision = '00b26f48ff32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_modified', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_modified')
    # ### end Alembic commands ###
